version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: bingo-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bingo

volumes:
  postgres_data: