name: Build Artifact Workflow

on:
  workflow_call:

jobs:
  building_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v4

      - name: SET UP JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: MVN CLEAN PACKAGE
        run: mvn clean package

      - name: UPLOAD BUILD ARTIFACT
        uses: actions/upload-artifact@v4
        with:
          name: bingoapp-backend-${{ github.run_number }}
#          path: target/github-actions-*.jar
          path: |
            .
            !.git/

