package com.yanajiki.application.bingoapp.database;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * JPA entity representing a player in a bingo room.
 * <p>
 * Each player has a display name and belongs to exactly one {@link RoomEntity}.
 * A unique constraint on {@code (name, room_id)} prevents duplicate player names
 * within the same room. Player names are allowed to be reused across different rooms.
 * </p>
 * <p>
 * Use the {@link #create(String, RoomEntity)} factory method to build a new player
 * ready for persistence.
 * </p>
 */
@Entity
@Table(name = "player", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"name", "room_id"})
})
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class PlayerEntity {

	/** Primary key, auto-generated by the database. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/** The player's display name. Maximum 50 characters. */
	@Column(nullable = false, length = 50)
	private String name;

	/**
	 * The room this player belongs to.
	 * Loaded lazily since listing players in a room does not require full room data.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	private RoomEntity roomEntity;

	/** Timestamp of when the player joined the room. Set automatically on insert. */
	@CreationTimestamp
	private LocalDateTime joinDateTime;

	/**
	 * Factory method to create a {@link PlayerEntity} for a given room.
	 * <p>
	 * Sets the name and room association; {@code joinDateTime} will be populated
	 * by {@link CreationTimestamp} upon persistence.
	 * </p>
	 *
	 * @param name       the player's display name
	 * @param roomEntity the room the player is joining
	 * @return a new, unpersisted {@link PlayerEntity} ready to be saved
	 */
	public static PlayerEntity create(String name, RoomEntity roomEntity) {
		PlayerEntity player = new PlayerEntity();
		player.setName(name);
		player.setRoomEntity(roomEntity);
		return player;
	}
}
